apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ordencompra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-ordencompra
  template:
    metadata:
      labels:
        app: app-ordencompra
    spec:
      containers:
        - name: app-ordencompra
          image: violentpanda1007/app-ordencompra
          env:
            - name: APP_ClIENTE_URL
              value: http://app-cliente-service:8080

            - name: APP_PRODUCTO_URL
              value: http://app-producto-service:8080
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-ordencompra-service
spec:
  type: ClusterIP
  selector:
    app: app-ordencompra
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080